import { Boss } from './boss';

export const BOSSES: Boss[] = [
    new Boss('Forsaken Thicket', 'Spirit Vale', 'Vale Guardian',
     { 'background-image': 'url(assets/bosses/vg.png)' }, 'vg', 'Vale Guardian'),
    new Boss('Forsaken Thicket', 'Spirit Vale', 'Gorseval',
     { 'background-image': 'url(assets/bosses/gorse.png)' }, 'gorse', 'Gorseval the Multifarious'),
    new Boss('Forsaken Thicket', 'Spirit Vale', 'Sabetha',
     { 'background-image': 'url(assets/bosses/sab.png)' }, 'sab', 'Sabetha the Saboteur'),
    new Boss('Forsaken Thicket', 'Salvation Pass', 'Slothasor',
     { 'background-image': 'url(assets/bosses/sloth.png)' }, 'sloth', 'Slothasor'),
    new Boss('Forsaken Thicket', 'Salvation Pass', 'Matthias',
     { 'background-image': 'url(assets/bosses/matt.png)' }, 'matt', 'Matthias Gabrel'),
    new Boss('Forsaken Thicket', 'Fortress of the Faithful', 'Keep Construct',
        { 'background-image': 'url(assets/bosses/kc.png)' }, 'kc', 'Keep Construct'),
    new Boss('Forsaken Thicket', 'Fortress of the Faithful', 'Xera',
     { 'background-image': 'url(assets/bosses/xera.png)' }, 'xera', 'Xera'),
    new Boss('Bastion of the Penitent', 'Bastion of the Penitent', 'Cairn',
        { 'background-image': 'url(assets/bosses/cairn.png)' }, 'cairn', 'Cairn the Indomitable'),
    new Boss('Bastion of the Penitent', 'Bastion of the Penitent', 'Mursaat',
        { 'background-image': 'url(assets/bosses/mo.png)' }, 'mo', 'Mursaat Overseer'),
    new Boss('Bastion of the Penitent', 'Bastion of the Penitent', 'Samarog',
        { 'background-image': 'url(assets/bosses/sam.png)' }, 'sam', 'Samarog'),
    new Boss('Bastion of the Penitent', 'Bastion of the Penitent', 'Deimos',
        { 'background-image': 'url(assets/bosses/dei.png)' }, 'dei', 'Deimos')/*,
    new Boss('Fractals', 'Nightmare', 'MAMA',
     { 'background-image': 'url(assets/bosses/mama.png)' }, 'mama', 'MAMA'),
    new Boss('Fractals', 'Nightmare', 'Siax',
     { 'background-image': 'url(assets/bosses/siax.png)' }, 'siax', 'Siax'),
    new Boss('Fractals', 'Nightmare', 'Ensolyss',
     { 'background-image': 'url(assets/bosses/enso.png)' }, 'enso', 'Ensolyss'),
    new Boss('Fractals', 'Shattered Observatory', 'Skorvald',
     { 'background-image': 'url(assets/bosses/sko.png)' }, 'sko', 'Skorvald'),
    new Boss('Fractals', 'Shattered Observatory', 'Artsariiv',
     { 'background-image': 'url(assets/bosses/art.png)' }, 'art', 'Artsarriv'),
    new Boss('Fractals', 'Shattered Observatory', 'Arkk',
     { 'background-image': 'url(assets/bosses/arkk.png)' }, 'arkk', 'Arkk')*/
];
